spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: connection1
      port: 27017
      host: localhost

server:
  port: ${PORT}
  servlet:
    context-path: /${my_career.api_prefix}/${my_career.api_version}/

my_career:
  api_prefix: ${API_PREFIX}
  api_version: ${API_VERSION}

  sms_aero:
    url: ${AERO_SMS_URL}
    email: ${AERO_EMAIL}
    api_key: ${AERO_API_KEY}
