spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: connection1
      port: 27017
      host: localhost

server:
#  port: ${PORT}
#  servlet:
#    context-path: /${my_career.api_prefix}/${my_career.api_version}/
  port: 8080
  servlet:
    context-path: /${my_career.api_prefix}/${my_career.api_version}/

my_career:
  api_prefix: api
  api_version: 1.0

  sms_aero:
    url: https://gate.smsaero.ru/v2/
    email: dmitry.fominenkov@gmail.com
    api_key: L9aresl57pue1O3THkUlMXqyyiUV
